# Generated by Django 3.1.4 on 2021-02-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnippetsModel',
            new_name='Snippet',
        ),
    ]
